### ISSUE TITLE
Bug: server list keeps jumping to the beginning

### ISSUE THREAD

**Issue by ticklemyIP** [Windscribe/Android-App#26]
Usually when I open the app and start scrolling in the server list, the app jumps back at the start of the list for some reason. This can be a bit annoying. I attached a recording below.

https://github.com/user-attachments/assets/0757b09e-7db2-4196-91a8-4399c8efc420

**Comment by Ginder-Singh** [comment]
[Fixed here](https://github.com/Windscribe/Android-App/releases/latest)

**Comment by ticklemyIP** [comment]
Hey, just so you know this is still happening sometimes in the latest build.
